
fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.13.1'
    powershell:
      repo: 'git://github.com/puppetlabs/puppetlabs-powershell.git'
      ref: '2.0.3'	  
  symlinks:
    timezone_win: "#{source_dir}"